version: '3.8'

services:
  nginx:
    build:
      context: .
    image: autotable-nginx
    ports:
      - 80:80

  server:
    build:
      context: ./server
    image: autotable-server
