version: '3.8'

services:
  nginx:
    build:
      context: .
    image: autotable-nginx
    networks:
      - riichi-ingress
      - default

  server:
    build:
      context: ./server
    image: autotable-server

networks:
  riichi-ingress:
    external: true
    internal: true
